name: Manual | GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  github-actions-input-demo:
    uses: JohanRN/testing_1/.github/workflows/main.yml@main
